### ISSUE TITLE
Investigate proximity cut

### ISSUE THREAD

**Issue by kirsty-duffy** [kirsty-duffy/uB-CC1pi#16]
Put a cut on how close the PFPs start to the reco vertex (5cm seems reasonable, but can we tune more?)

**Comment by AleshaDevitt** [comment]
Considered two different versions of the cut:
- If we add this in addition to asking what pandora thinks the daughters are (so “daughters” actually means “pandora thinks it’s a daughter and track starts within x cm”) what happens?
- If we add this instead of asking what pandora thinks the daughters are (so “daughters” just means “track in the TPCObject that starts within x cm”) what happens?

At least in isolation (so without trying to combine it with other cuts):
- A very loose cut is best.
- These two different versions of the cut give nearly the same results (<1% difference in eff and pur).
- They only improve marginally over just requiring two daughters. Marco's selection has eff/pur of 51.8%/12.7%; >=2 daughters has 49.8%/15.7%; >=2 daughters within 14cm has 48.5%/15.9% if we look at the Pandora hierarchy and 48.8%/16.0% if we don't.

Also considered a third, more event-level version of the cut: if any track is farther away than a certain distance, fail the whole event. This was very similar to the other two.
